use_frameworks!

platform :ios, '8.0'

target 'BinartOCAMR_Example' do
  pod 'BinartOCAMR', :path => '../'

  target 'BinartOCAMR_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
